### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by AdrianFarrel** [ietf/terminology#22]
An old one that I recall in the IBM style guide from 30 years ago.
Please consider offering "not valid".

**Comment by larseggert** [comment]
FYI, I disabled this check again in fb6024a8f53bcc5beddf755f6f7cc64a4803b63c. We've seem numerous authors that are confused by the guidance and end up picking a substitution that is less clear.

**Comment by JayDaley** [comment]
I’m pretty sure that we’re mixing up the two meanings of "invalid" here.  There is a strong view that "invalid" should not be used in place of "person with disability" because it infers lower worth, but I cannot find anyone objecting to using it to mean "not valid".  Since our documents are highly unlikely to refer to a person with disability in this way, it seems best not to include this check.

**Comment by AdrianFarrel** [comment]
I’m not going to fight this. But just to say that:

*	The IBM documentation standards have advised against the use of “invalid” for more than 30 years
*	It is perfectly reasonable to substitute with “not valid”

 

This provides a very good example of “I know it when I see it” and is good evidence that attempting to formulate lists of words that are or are not allowed is inadvisable. 

 

While fully accepting that the use of “traditional” should be avoided even it is used to mean “historical” and without implications of specific native American history, I cannot see how the distinction that Jay makes can be carried through. That is, it is not the context in which the word is used that renders it a poor choice, but the associated meaning of the word and the connotations that are carried.

 

Hey, ho. There are bigger things to worry about, and rather than applying lists and rules, it would be better if we reviewed our text compassionately.

 

Thanks,

Adrian

**Comment by JayDaley** [comment]
The problem with "not valid" is that it is clumsy when used as a direct replacement to an attributive adjective - i.e. "an invalid subject" -> "a not valid subject" and it's not immediately obvious how to tidy up a substitution.  Some guidance might get around that though I still think we're mixing meanings.  

Also, I thought the issue with "traditional" was not any association with American history but the ambiguity of its meaning, which is why "historical" is one possible substitution, but equally "previously recommended" or "widespread" might work depending on the context.
